import React, { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'

import { preview } from '../assets'
import { getRandomPrompt } from '../utils'
import { FormField, Loader } from '../components'

const CreatePost = () => {
  const navigate = useNavigate()
  const [form, setform] = useState(
    {
      name: '', 
      prompt: '', 
      image: ''
    }
  );

  const [generatingImage, setgeneratingImage] = useState(false)
  const [loading, setloading] = useState(false)

  const generateImage = () => {}
  const handleSubmit = () => {}
  const handleChange = (e) => {
    setform({ ...form, [e.target.name]: e.target.value})
  }
  const handleSupriseMe = () => {
    const randomPrompt = getRandomPrompt(form.prompt)
    setform({ ...form, prompt:randomPrompt})
  }

  return (
    <section className='max-w-7xl mx-auto text-left'>
      <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]'>
          Create Logo
        </h1>
        <p className='mt-2 text-[#666e75] max-w[500px]'>
          Create a collection of imaginative and visually stunning logos generated by our AI and share with the Community
        </p>
      </div>

      <form className='mt-16 max-w-3x1' onSubmit={handleSubmit}>
        <div className='flex flex-col gap-5'>
          <FormField 
            labelName="name"
            type="text"
            name="name"
            placeholder="John Doe"
            value={form.name}
            handleChange={handleChange}            
          />
          <FormField 
            labelName="prompt"
            type="text"
            name="prompt"
            placeholder="A pencil and watercolor drawing of a bright city in the future with flying cars"
            value={form.prompt}
            handleChange={handleChange}
            isSuprise
            handleSupriseMe={handleSupriseMe}           
          />
          <div className='relative bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 w-64 p-3 h-64 flex justify-center items-center'>
            {
              form.photo ? (
                <img
                 src={form.image}
                 alt={form.prompt}
                 className='w-full h-full object-contain'
                >
                </img>
              ): 
                <img
                  src={preview}
                  alt='preview'
                  className='w-9/12 h-9/12 object-contain opacity-40'
                >
                </img>
            }
            {
              generatingImage && (
                <div className='absolute inset-0 z-o flex justify-center items-center bg-[rgba(0,0,0,0.5)] rounded-lg'>
                  <Loader />
                </div>
              )
            }
          </div>
        </div>
        <div className='mt-5 flex gap-5'>
          <button
            type='button'
            onClick={generateImage}
            className='text-white text-center text-sm w-full sm-w:auto px-5 py-2.5 rounded-md font-medium bg-green-700 '
          >
            {generatingImage ? 'Generating...' : 'Generate'}
          </button>
        </div>

        <div className='md-10'>
          <p className='mt-2 text-[#666e75] text-[14px]'>
            Once you have generated the Image, you can share it with the Community
          </p>
          <button
             type='submit'
             className='mt-3 text-white bg-[#6469ff] font-medium rounded-md text-sm w-full sm:w-auto px-5 py-2.5 text-center'
          >
            {loading ? 'Share': 'Share with Community'}
          </button>
        </div>
      </form>
    </section>
  )
}

export default CreatePost