import React, { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'

import { preview } from '../assets'
import { getRandomPrompt } from '../utils'
import { FormField, Loader } from '../components'

const CreatePost = () => {
  const navigate = useNavigate()
  const [form, setform] = useState(
    {
      name: '', 
      prompt: '', 
      image: ''
    }
  );

  const [generatingImage, setgeneratingImage] = useState(false)
  const [loading, setloading] = useState(false)

  const handleSubmit = () => {}
  const handleChange = (e) => {}
  const handleSupriseMe = (e) => {}

  return (
    <section className='max-w-7xl mx-auto text-left'>
      <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]'>
          Community Showcase
        </h1>
        <p className='mt-2 text-[#666e75] max-w[500px]'>
          Create a collection of imaginative and visually stunning logos generated by our AI and share with the Community
        </p>
      </div>

      <form className='mt-16 max-w-3x1' onSubmit={handleSubmit}>
        <div className='flex flex-col gap-5'>
          <FormField 
            labelName="name"
            type="text"
            name="name"
            placeholder="John Doe"
            value={form.name}
            handleChange={handleChange}            
          />
          <FormField 
            labelName="prompt"
            type="text"
            name="name"
            placeholder="A pencil and watercolor drawing of a bright city in the future with flying cars"
            value={form.prompt}
            handleChange={handleChange}
            isSuprise
            handleSupriseMe={handleSupriseMe}           
          />
        </div>
      </form>
    </section>
  )
}

export default CreatePost